apiVersion: v1
kind: Service
metadata:
  name: chiron-service
spec:
  type: ClusterIP
  selector:
    app: chiron-worker
  ports:
    - protocol: TCP
      port: 83       # Port that the service will expose
      targetPort: 6003 # Port that the application is running on