apiVersion: v1
kind: Service
metadata:
  name: sacall-service
spec:
  type: ClusterIP
  selector:
    app: sacall-worker
  ports:
    - protocol: TCP
      port: 81       # Port that the service will expose
      targetPort: 6000 # Port that the application is running on