apiVersion: v1
kind: Service
metadata:
  name: catcaller-service
spec:
  type: ClusterIP
  selector:
    app: catcaller_worker
  ports:
    - protocol: TCP
      port: 80       # Port that the service will expose
      targetPort: 5000 # Port that the application is running on