apiVersion: apps/v1
kind: Deployment
metadata:
  name: catcaller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catcaller-worker
  template:
    metadata:
      labels:
        app: catcaller-worker
    spec:
      containers:
      - name: catcaller-worker
        image: drigix/catcaller-jetson-nano:latest
        resources:
          limits:
            nvidia.com/gpu: 1 # Request one GPU
        ports:
        - containerPort: 6002
        env:
        - name: CATCALLER_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName