apiVersion: v1
kind: Service
metadata:
  name: rodan-service
spec:
  type: ClusterIP
  selector:
    app: rodan-worker
  ports:
    - protocol: TCP
      port: 84       # Port that the service will expose
      targetPort: 6004 # Port that the application is running on